---
# The template platform supports sensors which break out state_attributes from other entities.
#
# https://www.home-assistant.io/components/sensor.template/
#

- platform: template
  sensors:
    sensor_voordeur:
      device_class: door
      friendly_name: Voordeur
      value_template: >
        {{ states.sensor.fibaro_door_sensor_hal_begane_grond_access_control.state < '23' }}
