---
- alias: System - Check automations status
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: '/1'
  action:
    # - delay: 00:00:30
    - service: python_script.all_automations_counter
    - service: python_script.on_automations_counter
    # - service: python_script.latest_commit
