---
#################
# Battery sensors
#################
#
# Z-wave
- platform: template
  sensors:
    zwave_battery_smoke_sensor_begane_grond:
      value_template: '{{ states.zwave.fibaro_smoke_sensor_gang_begane_grond.attributes.battery_level }}'
      friendly_name: Smoke sensor | begane grond
      unit_of_measurement: "%"
      device_class: battery

- platform: template
  sensors:
    zwave_battery_smoke_sensor_slaapkamer_zolder:
      value_template: '{{ states.zwave.fibaro_smoke_sensor_slaapkamer_zolder.attributes.battery_level }}'
      friendly_name: Smoke sensor | slaapkamer zolder
      unit_of_measurement: "%"
      device_class: battery

- platform: template
  sensors:
    zwave_battery_door_sensor_hal_begane_grond:
      value_template: '{{ states.zwave.fibaro_door_sensor_hal_begane_grond.attributes.battery_level }}'
      friendly_name: Door sensor | begane grond
      unit_of_measurement: "%"
      device_class: battery

- platform: template
  sensors:
    zwave_battery_motion_sensor_hal_begane_grond:
      value_template: '{{ states.zwave.fibaro_motion_sensor_hal_begane_grond.attributes.battery_level }}'
      friendly_name: Motion sensor | begane grond
      unit_of_measurement: "%"
      device_class: battery

# Device Trackers
- platform: template
  sensors:
    battery_phone_klaas:
      value_template: '{{ states.device_tracker.telefoon_klaas.attributes.battery_level | round(0)}}'
      friendly_name: Telefoon batterij | Klaas
      unit_of_measurement: '%'
      device_class: battery

- platform: template
  sensors:
    battery_phone_marlene:
      value_template: '{{ states.device_tracker.telefoon_marlene.attributes.battery_level | round(0)}}'
      friendly_name: Telefoon batterij | Marlene
      unit_of_measurement: '%'
      device_class: battery
